config/routes.rb
Rails.application.routes.draw do
  get 'people/index'
  get 'people/show'
  get 'people/edit'
  get 'people/new'
 resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :document
    belongs_to :role
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def show
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end


  private

  def person_params
    params.require(:person).permit(:identificacion, :primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :document_id, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <main class ="container">
  <section class ="row">
  <aside class ="col-md-4">
  <div =class="list-group">
  <a href="hola" class ="list.group-item list-group-item-action active" aria-current="true">
 
  </a>
  <a href="<%= new_person_path%>" class="list-group-item list-group-item-action active ">registrar persona</a>
 

  </div>
  </aside>
 
  <article class = "col-md-8">
   <%= yield %>
  </article>

  </section>
  </main>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
    <%= f.association :document, label_method: :tipo_documento %>
    <%= f.input :identificacion %>
    <%= f.input :primer_nombre %>
    <%= f.input :segundo_nombre %>
    <%= f.input :primer_apellido %>
    <%= f.input :segundo_apellido %>
    <%= f.association :role, label_method: :tipo_rol %>
    <%= f.button :submit %>
  <% end %>

app/views/people/_person.html.erb
<tr>
  <th scope="row"><%= person.id %></th>
  <td><%= person.document.tipo_documento %></td>
  <td><%= link_to person.identificacion, person_path(person.id), class: "text-danger" %></td>
  <td><%= person.primer_nombre %></td>
  <td><%= person.segundo_nombre %></td>
  <td><%= person.primer_apellido %></td>
  <td><%= person.segundo_apellido %></td>
  <td><%= person.role.tipo_rol %></td>
</tr>

app/views/people/edit.html.erb
<%= render 'form' %>

app/views/people/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Tipo de identificación</th>
      <th scope="col">Identificación</th>
      <th scope="col">Primer nombre</th>
      <th scope="col">Segundo nombre</th>
      <th scope="col">Primer apellido</th>
      <th scope="col">Segundo apellido</th>
      <th scope="col">Rol</th>
    </tr>
  </thead>
  <tbody>
    <%= render @people %>
  </tbody>
</table>

app/views/people/new.html.erb
<%= render 'form' %>

app/views/people/show.html.erb
<dl class="person-details">
  <dt>Tipo de identificación</dt>
  <dd><%= @person.document.tipo_documento %></dd>
  <dt>Identificación</dt>
  <dd><%= @person.identificacion %></dd>
  <dt>Primer nombre</dt>
  <dd><%= @person.primer_nombre %></dd>
  <dt>Segundo nombre</dt>
  <dd><%= @person.segundo_nombre %></dd>
  <dt>Primer apellido</dt>
  <dd><%= @person.primer_apellido %></dd>
  <dt>Segundo apellido</dt>
  <dd><%= @person.segundo_apellido %></dd>
  <dt>Tipo</dt>
  <dd><%= @person.role.tipo_rol %></dd>
</dl>

<div class="button-container">
  <a href="<%= edit_person_path %>" class="btn btn-primary active">Editar</a>
  <a href="<%= people_path %>" class="btn btn-secondary">Volver</a>
</div>